### ISSUE TITLE
Improve code readability

### ISSUE THREAD

**Issue by antarikshc** [antarikshc/TheGuardianNews#4]
Any kinds of improvements are welcome. (OOPs concepts, Design Patterns, Comments, etc)

**Comment by ngwutadesmond** [comment]
Can I pick this up? not good with KOTLIN yet but I can make the code look better with JAVA

**Comment by antarikshc** [comment]
> Can I pick this up? not good with KOTLIN yet but I can make the code look better with JAVA

Hey, we are currently moving to Kotlin, so improving Java codebase would be a wasted effort. Can you hold on for a bit till we migrate to Kotlin.

**Comment by antarikshc** [comment]
I'll reopen this once we are migrated to Kotlin

**Comment by ngwutadesmond** [comment]
Alright, that's great. thanks
